
CREATE OR REPLACE TABLE FACT_SALES (
  SALESHEADERID INT NOT NULL,
  SALESDETAILID INT NOT NULL,
  DIMPRODUCTID INT CONSTRAINT FK_PRODUCTID FOREIGN KEY REFERENCES DIM_PRODUCT(DIMPRODUCTID),
  DIMSTOREID INT CONSTRAINT FK_STOREID FOREIGN KEY REFERENCES DIM_STORE(DIMSTOREID),
  DIMRESELLERID INT CONSTRAINT FK_RESELLERID FOREIGN KEY REFERENCES DIM_RESELLER(DIMRESELLERID),
  DIMCUSTOMERID INT CONSTRAINT FK_CUSTOMERID FOREIGN KEY REFERENCES DIM_CUSTOMER(DIMCUSTOMERID),
  DIMCHANNELID INT CONSTRAINT FK_CHANNELID FOREIGN KEY REFERENCES DIM_CHANNEL(DIMCHANNELID),
  DATE_PKEY NUMBER(9) CONSTRAINT FK_DATE FOREIGN KEY REFERENCES DIM_DATE(DATE_PKEY),
  DIMLOCATIONID INT CONSTRAINT FK_LOCATIONID FOREIGN KEY REFERENCES DIM_LOCATION(DIMLOCATIONID),
  SALE_AMOUNT NUMERIC(8,2),
  SALE_QUANTITY INT,
  SALE_UNIT_PRICE NUMERIC(8,2),
  SALE_EXTENDED_COST NUMERIC(8,2),
  SALE_TOTAL_PROFIT NUMERIC(8,2)
)



INSERT INTO FACT_SALES(
  SALESHEADERID,
  SALESDETAILID,
  DIMPRODUCTID,
  DIMSTOREID,
  DIMRESELLERID,
  DIMCUSTOMERID,
  DIMCHANNELID,
  DATE_PKEY,
  DIMLOCATIONID,
  SALE_AMOUNT,
  SALE_QUANTITY,
  SALE_UNIT_PRICE,
  SALE_EXTENDED_COST,
  SALE_TOTAL_PROFIT
)
SELECT SH.SALES_HEADER_ID,
       SD.SALES_DETAILS_ID,
       DP.DIMPRODUCTID,
       NVL(DS.DIMSTOREID, -1) AS DIMSTOREID,
       NVL(DR.DIMRESELLERID, -1) AS DIMRESELLERID,
       NVL(DC.DIMCUSTOMERID, -1) AS DIMCUSTOMERID,
       DCH.DIMCHANNELID,
       CAST(REPLACE(REPLACE(CAST(SH.DATE AS DATE), '00', '20'), '-', '') AS NUMBER(9)) AS DATE_PKEY,
       COALESCE(DS.DIMLOCATIONID, DC.DIMLOCATIONID, DR.DIMLOCATIONID, -1) AS DIM_LOCATIONID,
       SD.SALES_AMT,
       SD.SALES_QTY,
       CASE WHEN DR.DIMRESELLERID IS NOT NULL THEN DP.PRODUCTWHOLESALEPRICE ELSE DP.PRODUCTRETAILPRICE END AS SALE_UNIT_PRICE,
       ROUND(DP.PRODUCTCOST * SD.SALES_QTY,2) AS SALE_EXTENDED_COST,
       ROUND(SD.SALES_AMT - SALE_EXTENDED_COST,2) AS SALE_TOTAL_PROFIT
FROM STG_SALES_HEADER AS SH
INNER JOIN STG_SALES_DETAILS AS SD ON SH.SALES_HEADER_ID = SD.SALES_HEADER_ID
INNER JOIN DIM_PRODUCT AS DP ON SD.PRODUCT_ID = DP.DIMPRODUCTID
INNER JOIN DIM_CHANNEL AS DCH ON SH.CHANNEL_ID = DCH.DIMCHANNELID
LEFT JOIN DIM_STORE AS DS ON SH.STORE_ID = DS.DIMSTOREID
LEFT JOIN DIM_RESELLER AS DR ON SH.RESELLER_ID = DR.RESELLERID
LEFT JOIN DIM_CUSTOMER AS DC ON SH.CUSTOMER_ID = DC.CUSTOMERID
           

CREATE OR REPLACE TABLE FACT_PRODUCT_TARGET(
  DIMPRODUCTID INT CONSTRAINT FK_PRODID FOREIGN KEY REFERENCES DIM_PRODUCT(DIMPRODUCTID),
  DATE_PKEY NUMBER(9) CONSTRAINT FK_DATEKEY FOREIGN KEY REFERENCES DIM_DATE(DATE_PKEY),
  TARGET_SALES_QUANTITY NUMBER(8,2)
)

INSERT INTO FACT_PRODUCT_TARGET(
  DIMPRODUCTID,
  DATE_PKEY,
  TARGET_SALES_QUANTITY
)
SELECT DP.DIMPRODUCTID, DD.DATE_PKEY, ROUND(SPTD.SALES_QTY_TARGET/365, 2) AS TARGET_SALES_QUANTITY
FROM DIM_PRODUCT AS DP 
INNER JOIN STG_PRODUCT_TARGET_DATA AS SPTD ON DP.DIMPRODUCTID = SPTD.PRODUCT_ID
INNER JOIN DIM_DATE AS DD ON SPTD.YEAR = DD.YEAR


CREATE OR REPLACE TABLE FACT_SRC_TARGET(
  DIMCHANNELID INT CONSTRAINT FK_CHNNLID FOREIGN KEY REFERENCES DIM_CHANNEL(DIMCHANNELID),
  DIMSTOREID INT CONSTRAINT FK_STRID FOREIGN KEY REFERENCES DIM_STORE(DIMSTOREID),
  DIMRESELLERID INT CONSTRAINT FK_RESELLID FOREIGN KEY REFERENCES DIM_RESELLER(DIMRESELLERID),
  DATE_PKEY NUMBER(9) CONSTRAINT FK_DATEID FOREIGN KEY REFERENCES DIM_DATE(DATE_PKEY),
  TARGET_SALES_AMOUNT NUMBER(12,2)
)

INSERT INTO FACT_SRC_TARGET(
  DIMCHANNELID,
  DIMSTOREID,
  DIMRESELLERID,
  DATE_PKEY,
  TARGET_SALES_AMOUNT
)
SELECT DCH.DIMCHANNELID,
       NVL(DS.DIMSTOREID,-1) AS DIMSTOREID,
       NVL(DR.DIMRESELLERID,-1) AS DIMRESELLERID,
       DD.DATE_PKEY,
       ROUND(SCRSTD.TARGET_SALES_AMT/365,2) AS TARGET_SALES_AMOUNT
FROM STG_CHANNEL_RESELLER_STORE_TARGET_DATA AS SCRSTD
INNER JOIN DIM_CHANNEL AS DCH ON DCH.CHANNELNAME = CASE WHEN SCRSTD.CHANNEL_NAME = 'Online' THEN 'On-line' ELSE SCRSTD.CHANNEL_NAME END
LEFT JOIN DIM_STORE AS DS ON DS.STORENUMBER = CASE WHEN SCRSTD.TARGET_NAME = 'Store Number 5' THEN 5
                                                                        WHEN SCRSTD.TARGET_NAME = 'Store Number 8' THEN 8
                                                                        WHEN SCRSTD.TARGET_NAME = 'Store Number 10' THEN 10
                                                                        WHEN SCRSTD.TARGET_NAME = 'Store Number 21' THEN 21
                                                                        WHEN SCRSTD.TARGET_NAME = 'Store Number 34' THEN 34
                                                                        WHEN SCRSTD.TARGET_NAME = 'Store Number 39' THEN 39 
                                               END
LEFT JOIN DIM_RESELLER AS DR ON DR.RESELLERNAME = SCRSTD.TARGET_NAME
LEFT JOIN DIM_DATE AS DD ON SCRSTD.YEAR = DD.YEAR
